from numpy import cos, pi

CONTROLLER_POLL_RATE = 0.05
MCU_BAUD_RATE = 115200
JOYSTICK_DEADZONE = 0.05
TRIGGER_DEADZONE = 0.1

TENDON_1_ANGLE = 0.5 * pi
TENDON_2_ANGLE = -5 * pi / 6
TENDON_3_ANGLE = -1 * pi / 6

MIN_SPOOL_SPEED = -2.5  # rpm
MAX_SPOOL_SPEED = 2.5  # rpm

MAX_TENDON_SPEED = 60

BODY_DIAMETER = 0.0762  # Meters (3 inches)
TENDON_SPOOL_DIAMETER = 0.0254  # Meters (1 inch)
BODY_RADIUS = BODY_DIAMETER / 2
TENDON_SPOOL_RADIUS = TENDON_SPOOL_DIAMETER / 2

MAX_CURVE = 1.5  # radians per meter
MAX_TENDON_VALUE = (MAX_CURVE * BODY_RADIUS * cos(0)) / TENDON_SPOOL_RADIUS


class MCU_PRAMS:
    TENDON_MOTOR_SPEED = 0x00
