from math import pi

CONTROLLER_POLL_RATE = 0.01
MCU_BAUD_RATE = 115200
JOYSTICK_DEADZONE = 0.05
TRIGGER_DEADZONE = 0.1

TENDON_1_ANGLE = 0
TENDON_2_ANGLE = 2 * pi / 3
TENDON_3_ANGLE = 4 * pi / 3

BODY_DIAMETER = 0.0254  # Meters (3 inches)
TENDON_SPOOL_DIAMETER = 0.0254  # Meters (1 inch)
BODY_RADIUS = BODY_DIAMETER / 2
TENDON_SPOOL_RADIUS = TENDON_SPOOL_DIAMETER / 2

MAX_CURVE = 1.5  # radians per meter
